{% set name = "interpax" %}
{% set version = "0.3.10" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/f0uriest/interpax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 00546b89071d0863dade13199538354dff9d90e5b0b07f90852d6c00f8815484

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer
  run:
    - jaxtyping >=0.2.24,<0.4.0
    - lineax >=0.0.5,<=0.0.8
    - python >={{ python_min }}
    - equinox >=0.11.0,<0.14
    - jax >=0.4.30,<0.8
    - numpy >=1.20.0,<2.4

test:
  imports:
    - interpax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/f0uriest/interpax
  summary: Interpolation and function approximation with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
