{% set name = "interpax" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/interpax-{{ version }}.tar.gz
  sha256: db8d12b9d13d9c2f0788375bc035e4f6f3c0b2b5e70d0e699a272b4c0b0757e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer-518
  run:
    - python >={{ python_min }}
    - equinox >=0.11,<0.12
    - jax >=0.3.2,<0.5.0
    - numpy >=1.20.0,<2.2

test:
  imports:
    - interpax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/f0uriest/interpax
  summary: Interpolation and function approximation with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
