{% set name = "interpax" %}
{% set version = "0.3.13" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/f0uriest/interpax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5b29955b9e2cb8c8500a775732b9d646fbd14096428fed7d4862786db072d58d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer
  run:
    - jaxtyping >=0.2.24,<0.4
    - lineax >=0.0.5,<=0.1.0
    - python >={{ python_min }}
    - equinox >=0.11.0,<0.14
    - jax >=0.4.30,<0.10
    - numpy >=1.20.0,<2.5

test:
  imports:
    - interpax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/f0uriest/interpax
  summary: Interpolation and function approximation with JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
